// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class PlayGameInstance_old:IPlayGame
{
	public static PlayGameInstance_old INSTANCE;
	PlaySceneController_old pSC;
	public PlaySceneController_old PSC {
		get { return pSC;}
		set { pSC = value;}
	}
	public delegate void OnGameResult_Delegate ();
	public OnGameResult_Delegate  OnGameResultDelegate;


	public void OnGameResult ()
	{
		OnPause();

		if (OnGameResultDelegate != null)
			OnGameResultDelegate ();
	}

	public PlayGameInstance_old (PlaySceneController_old pSC)
	{
		this.pSC = pSC;
		INSTANCE = this;
	}

	public void OnStart ()
	{
		pSC.OnStart ();
	}
	
	public void OnReStart ()
	{
		pSC.OnRestart ();
	}
	
	public void OnPause ()
	{
		pSC.OnPause ();
	}
	
	public  void OnResume ()
	{
		pSC.OnResume ();
	}

	public void OnVectory ()
	{

	}

	public void OnFailed ()
	{

	}

	public void OnTouchDown(){
		pSC.PC.OnTouchDown();
	}

}


