// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class PlayGameInstance:IPlayGame
{
	public static PlayGameInstance INSTANCE;
	IPlayGameOver pGOInstance;

	public IPlayGameOver PGOInstance {
		get { return pGOInstance;}
		set { pGOInstance = value;}
	}

	PlaySceneController pSC;

	public PlaySceneController PSC {
		get { return pSC;}
		set { pSC = value;}
	}

	public PlayGameInstance (PlaySceneController pSC, IPlayGameOver pGOInstance)
	{
		this.pGOInstance = pGOInstance;
		this.pSC = pSC;
		INSTANCE = this;
	}

	public void OnStart ()
	{
		pSC.OnStart ();
	}
	
	public void OnReStart ()
	{
		pSC.OnRestart ();
	}
	
	public void OnPause ()
	{
		pSC.OnPause ();
	}
	
	public  void OnResume ()
	{
		pSC.OnResume ();
	}

	public void OnVectory ()
	{
		pGOInstance.OnVictory ();
	}

	public void OnFailed ()
	{
		pGOInstance.OnFailed ();
	}

}


